---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      deps-dktunited:
        patterns:
          - dktunited/*
      deps-external:
        patterns:
          - '*'
        exclude-patterns:
          - dktunited/*
